import json


def profitability_analysis(project_name: str, cost: float, revenue: float, project_time_frame: str):
    """
    Calculate the profitability of a project based on its costs, revenues and time frame.

    Args:
        project_name (str): The name of the project.
        cost (float): The total cost of the project in dollars.
        revenue (float): The total revenue generated by the project in dollars.
        project_time_frame (str): A string representing the time frame for which  the project is being run.

    Returns:
        dict: A dictionary containing the project's name, net profit, gross profit margin, return on costs,
              and profit_margin_per_month in a json format.
    """
    no_months = int(project_time_frame.split(' ')[0])
    no_months *= 12 if 'Year' in project_time_frame or 'year' in project_time_frame else 1
    net_income = revenue - cost
    gross_profit_margin = net_income / revenue * 100
    return_on_costs = net_income / cost * 100
    profit_margin_per_month = net_income / no_months
    data = {
        "project": project_name,
        "net_income": net_income,
        "gross_profit_margin": str(gross_profit_margin) + " %",
        "return_on_costs": str(return_on_costs) + " %",
        "profit_margin_per_month": profit_margin_per_month
    }
    return json.dumps(data)


def main():
    """Main driver program to test the functions."""
    result = profitability_analysis("Test Project", 600000, 1500000, "1 year")
    print(result)


if __name__ == "__main__":
    main()
